# Generated by Django 5.0.3 on 2024-05-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(default='write later', max_length=255),
        ),
    ]
