# Generated by Django 5.0.3 on 2024-06-05 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0009_post_header_image_alter_post_snippet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='header_image',
            new_name='image',
        ),
    ]
