# Generated by Django 5.0.3 on 2024-06-06 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0010_rename_header_image_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='header_image',
        ),
    ]
